
platform :ios, '10.0'

target 'MSSDKDemo' do

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/Avid-ly/iOS-CocoaPods-Spec.git'

# MSSDK
pod 'MSSDK', '4.0.0.1'

# MAX聚合
pod 'AppLovinSDK'
pod 'AppLovinMediationAdColonyAdapter'
pod 'AppLovinMediationChartboostAdapter'
pod 'AppLovinMediationFyberAdapter'
pod 'AppLovinMediationGoogleAdapter'
pod 'AppLovinMediationInMobiAdapter'
pod 'AppLovinMediationIronSourceAdapter'
pod 'AppLovinMediationFacebookAdapter'
pod 'AppLovinMediationUnityAdsAdapter'
pod 'AppLovinMediationVungleAdapter'
pod 'AppLovinMediationGoogleAdManagerAdapter'
pod 'AppLovinMediationByteDanceAdapter'
pod 'AppLovinMediationTapjoyAdapter'
pod 'AppLovinMediationSmaatoAdapter'

# TASDK
pod 'TASDK'

end
